name: Build cipherbook

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
      - 'v*.*.*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }} (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [ '3.11' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install OS packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          # Core runtime deps for the app and builder
          python -m pip install PyQt6 cryptography pyinstaller

      - name: Build executable
        run: |
          python -m PyInstaller --noconfirm --clean --onefile --windowed main.py --name cipherbook

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cipherbook-${{ runner.os }}-py${{ matrix.python-version }}
          path: |
            dist/cipherbook*
          if-no-files-found: error

  release:
    name: Publish Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
